sampling_dataset:
	K=50; \
	L="[30,20,10,5,2,1]" ; \
	SAVE_PATH=./data/adhd_microstate_dataset_samples; \
        python build_adhd_microstate_samples.py --K $$K --L $$L --save_base_path $$SAVE_PATH; \
