sampling_dataset:
	K=100; \
	L="[1,2,5,10,20,50]" ; \
	SAVE_PATH=./data/adhd_microstate_dataset_samples; \
        python build_adhd_microstate_samples.py --K $$K --L $$L --save_base_path $$SAVE_PATH; \
