syntax_analysis:
  grammar_file: "../data/grammar-trained.pcfg"
  input: "../data/test/recurrence_sentences/epileptic_eeg_dataset/sentence_converted/normal_integrated_all_d2_s4_converted.txt"
  repetition: "../data/test/recurrence_sentences/epileptic_eeg_dataset/normal_integrated_all_d2_s4_repetition.txt"
  log_intervals: 1000000
  log_path: "/data1/pcfg-log/test/logs/normal/"
  report_path: "/data1/pcfg-log/test/reports/normal/"
  serialize_to_files: true
  tree_serialization_path: "/data1/pcfg-log/test/serialized_tree/normal/"
  report_statistics: false
  sentence_from: -1
  sentence_to: -1