exp1-segmenting-dev-sequence:
	CONFIGURATION_PATH=./configs/epilepsy_all_person_intergrated-dev-normal-only.json; \
        PREEPILEPTIC_ZONE_LENGTH=120; \
	python dataset_splitting_and_segmentation.py -cf $$CONFIGURATION_PATH -pz $$PREEPILEPTIC_ZONE_LENGTH ;\
