syntax_analysis:
  grammar_file: "../data/grammar-trained.pcfg"
  input: "../data/recurrence_sentences/epileptic_eeg_dataset/sentence_converted/pre-epileptic_integrated_all_d2_s4_converted.txt"
  repetition: "../data/recurrence_sentences/epileptic_eeg_dataset/sentence_converted/pre-epileptic_integrated_all_d2_s4_repetition.txt"
  log_intervals: 1000000
  log_path: "/data1/pcfg-log/logs/pre-epileptic/"
  report_path: "/data1/pcfg-log/reports/pre-epileptic/"
  serialize_to_files: true
  tree_serialization_path: "/data1/pcfg-log/serialized_tree/pre-epileptic/"
  report_statistics: false
  sentence_from: -1
  sentence_to: -1
