syntax_analysis_exp1:
	BINARY_PATH=../lib/pcfg-cky-inside-outside/bin/syntax_analysis ; \
  	$$BINARY_PATH ./configurations/exp1/config_normal-test.yaml ; \
  	$$BINARY_PATH ./configurations/exp1/config_preepileptic.yaml ; \
  	$$BINARY_PATH ./configurations/exp1/config_seizure.yaml ; \

syntax_analysis_exp1-nogfp-no-normal-only:
	BINARY_PATH=../lib/pcfg-cky-inside-outside/bin/syntax_analysis ; \
        $$BINARY_PATH ./configurations/exp1-nogfp-no-normal-only/config_normal-test.yaml ; \
        $$BINARY_PATH ./configurations/exp1-nogfp-no-normal-only/config_preepileptic.yaml ; \
        $$BINARY_PATH ./configurations/exp1-nogfp-no-normal-only/config_seizure.yaml ; \

syntax_analysis_exp2:
	BINARY_PATH=../lib/pcfg-cky-inside-outside/bin/syntax_analysis ; \
	$$BINARY_PATH ./configurations/exp2-nogfp-no-normal-only/config_normal-test.yaml ; \
        $$BINARY_PATH ./configurations/exp2-nogfp-no-normal-only/config_preepileptic.yaml ; \
        $$BINARY_PATH ./configurations/exp2-nogfp-no-normal-only/config_seizure.yaml ; \

syntax_analysis_exp3:
	BINARY_PATH=../lib/pcfg-cky-inside-outside/bin/syntax_analysis ; \
	$$BINARY_PATH ./configurations/exp3-nogfp-no-normal-only/config_normal-test.yaml ; \
	$$BINARY_PATH ./configurations/exp3-nogfp-no-normal-only/config_preepileptic.yaml ; \
        $$BINARY_PATH ./configurations/exp3-nogfp-no-normal-only/config_seizure.yaml ; \
