phase_convert:
  grammar_file: "../data/pcfg/grammar.pcfg"
  input: "../data/test/recurrence_sentences/epileptic_eeg_dataset/seizure_integrated_all_d2_s4.txt"
  output: "../data/test/recurrence_sentences/epileptic_eeg_dataset/sentence_converted/seizure_integrated_all_d2_s4_converted.txt"
